### ISSUE TITLE
readme doc link is dead

### ISSUE THREAD

**Issue by mped-oticon** [rasmus-toftdahl-olesen/dog#18]
The link to http://halfdans.net/dog/ gives 404.

Maybe the documentation could move into the repo?
(I have a neat rst sphinx workflow that could be used :-)

regards, Mark

**Comment by rasmus-toftdahl-olesen** [comment]
Hi Mark - welcome to the project!

I have apparently switched domain names since that link was written :)

The documentation is in GitHub Pages (Jekyll) at the moment - but pull-requests are always welcome.
